### ISSUE TITLE
Quote Missing

### ISSUE THREAD

**Issue by TheHeroBrine422** [alemaninc/Exotic-Matter-Dimensions#11]
Hi. You appear to be missing an ending double quote on line 869 and it is causing my game to crash on launch.

**Comment by TheHeroBrine422** [comment]
Ok well, there were actually several missing quotes. I fixed them in a fork so I could try to continue to play and then I started getting some kind of null value errors coming from line 1342. I think that is coming from some kind of save fille issue due to me being on a fork rather than the code actually being broken.

If you want to know which lines were missing ending quotes it was lines 869, 888, 907, 926, 941, 956, 971, 986, 1078, and 1094.

**Comment by alemaninc** [comment]
Fixed
