### ISSUE TITLE
Mastery power becomes NaN, halting progress

### ISSUE THREAD

**Issue by johnachor** [alemaninc/Exotic-Matter-Dimensions#13]
Not exactly sure what causes this, but it happens to me frequently.  I can provide my save if needed.

![image](https://user-images.githubusercontent.com/18398407/179371161-d25be16a-9052-41de-a4c5-e2760729122d.png)

**Comment by johnachor** [comment]
Page refresh from this state resets mastery power to 0

**Comment by alemaninc** [comment]
There is a large update upcoming that will address the issue. Until then, at e5,543 stardust you are at or near the end of the curent content.
