### ISSUE TITLE
Infinite loading time

### ISSUE THREAD

**Issue by farciarz-funny** [alemaninc/Exotic-Matter-Dimensions#14]
I don't know why but it loading doesn't end

**Comment by Hedrauta** [comment]
can't confirm.... clear cache and try again, please!

**Comment by farciarz-funny** [comment]
How do i do that?

**Comment by Hedrauta** [comment]
Try CTRL+F5, otherwise it may depend on your browser.... Leme Google real quick......


https://its.uiowa.edu/support/article/719

There we go... 😉 If it still may not work, there might be blocking something the site

**Comment by farciarz-funny** [comment]
But im on mobile

**Comment by Hedrauta** [comment]
What kind of mobile... Android? Using Chrome? 


________________________________

**Comment by farciarz-funny** [comment]
Yes android

**Comment by farciarz-funny** [comment]
On android ( bruh the response i sent 5 hours ago didn't show up here )

**Comment by Hedrauta** [comment]
Dude..  I am at work... So chill please...

 Open your chrome, hit the 3 dots top right. Then settings > data privacy ( or just privacy, not sure bc I'm German),
> clear Browser history... Uncheck everything except cache, delete all time...

 try again... As I said before, if it may not work then, it's probably something on your phone, that blocks the site

________________________________

**Comment by marland34562** [comment]
i didnt know this bug existed until now!
