### ISSUE TITLE
cant load game due to Uncaught TypeError in achievements.js

### ISSUE THREAD

**Issue by breeze31** [alemaninc/Exotic-Matter-Dimensions#15]
![image](https://github.com/alemaninc/Exotic-Matter-Dimensions/assets/89343687/c16aa2ae-7d7c-408a-a18e-8f8417e021bc)

**Comment by breeze31** [comment]
i suspect the cause is line 1454 since the description is called differently then the rest of the code

**Comment by alemaninc** [comment]
The cause has been identified, it was actually due to a _news ticker_ that changes based on achievements and which broke the game completely for people with no achievements.
