### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by 70839** [alemaninc/Exotic-Matter-Dimensions#6]
The game won't load correctly.

**Comment by 70839** [comment]
![Screenshot 2022-02-25 2 04 38 PM](https://user-images.githubusercontent.com/100310011/155773208-54aa345f-7f40-4ffb-92e5-1f9a532ba11e.png)
its stuck on this screen

**Comment by Emjae** [comment]
> ![Screenshot 2022-02-25 2 04 38 PM](https://user-images.githubusercontent.com/100310011/155773208-54aa345f-7f40-4ffb-92e5-1f9a532ba11e.png) its stuck on this screen

JavaScript syntax error at line 46 (a closing parenthesis is missing). Waiting for [alemaninc](https://github.com/alemaninc).

**Comment by Hedrauta** [comment]
ye.... bugfix is already in #5 
just have to wait for dev to merge... 
if you can't wait,  open the page, hit F12, then enter into the Console the command:
`btoa(localstorage.getItem("save"))` and hit ↩ ( return )...
The popped up code can be copied ( which is your save )


fixed version is playable via `https://hedrauta.github.io/Exotic-Matter-Dimensions/` which has the fix #5 already in it 😏 
it just **can't** access your save from the original game 😉
 
![](https://i.imgur.com/Y1QG2uG.jpeg)

**Comment by 70839** [comment]
Thanks for your help. Once the import save started working, this game became just as good as Evolve by Demogorddon. I can't wait to see how much better this game becomes! Have a good day!
